### ISSUE TITLE
Add Imports explanations to contributing guide

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#162]
Currently we follow the following (non-standard to be clear, but useful) convention in `mmrm`:
- When only few functions from other packages are needed:
	- We want to use those only.
	- Therefore need to put the package in the `Imports`.
	- We always use `package::function()`.
	- We import (any random) single function from the package to make `R CMD check` happy.
- On the other hand, for completely imported packages such as `checkmate` we don't prefix with the package name.
We need to add this to the contributing guide.

**Comment by kkmann** [comment]
... and to clarify, we do not use `@importFrom` at all?

**Comment by BrianLang** [comment]
"We import (any random) single function from the package to make R CMD check happy." means we use `@importFrom`, right?

**Comment by danielinteractive** [comment]
@kkmann @BrianLang correct - we just use `@importFrom` once

**Comment by kkmann** [comment]
Sorry, my comment was not clear. I am just confused because it seems that @danielinteractive does not want to use @importFrom at all. 

I guess the question is whether we want to modfiy the namespace at all (@import/@importFrom) or not.

The downside of importing to the pkg namespace is that people could drop using :: (which we want). The advantage is that we do not need to maintain the Imports: field in the DESCRIPTION file manually (i.e. if all @import statements get dropped, the package will automatically be removed from the DESCRIPTION file).
