### ISSUE TITLE
Fix CRAN check problems

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#186]
https://cran.r-project.org/web/checks/check_results_mmrm.html

To do:

- [x] Make test `h_summarize_all_fits works as expected` not check the numbers themselves. We have other tests that check numbers. (To address https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/mmrm-00check.html and https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/mmrm-00check.html, so it seems this is `clang` related on Linux OS)
- [x] Write an issue for `testthat` repo to ask for advice on https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/mmrm-00check.html, see https://github.com/r-lib/testthat/issues/1715 -> solved, we just need to wait for new `testthat` version on CRAN

Note that we cannot and don't need to do anything about the installed package size (as these are just notes and we have tried this before already).
We need to correct this before 2022-12-19 to safely retain our package on CRAN.

**Comment by dgkf** [comment]
Running these tests in an `r-hub` container [does not reproduce these test failures](https://builder.r-hub.io/status/mmrm_0.1.5.tar.gz-02b82cea914d4f6bafe7ada0558a1f94).

Is it possible that this just randomly failed due to a failure to converge? If so, we might want to set the random seed if possible, or build in some fault tolerance - at least for when it runs on CRAN.

**Comment by danielinteractive** [comment]
@dgkf that is what I expected based on recent experiences from @gowerc - it should not be stochastic though, and also looking at the CRAN check results it does not seem stochastic, because the failure happens both on Fedora and on Debian clang systems. My "p-value" for this to be stochastic is very small. I suspect it is rather the specific compiler + system combination which we can't fully reproduce.

**Comment by dgkf** [comment]
The `r-hub` run I ran was on the same OS & compiler (fedora + clang). That's not saying it can't be system specific still, but there's a good chance that it's not solely due to OS or compiler.

Not only that, but this particular test is followed by the exact same optimizer fit. The same code used to fit [here](https://github.com/openpharma/mmrm/blob/c6d2d9c17d23e2fe02268754dbf5fbb22cc6554d/tests/testthat/test-fit.R#L139-L144) is also [repeated later](https://github.com/openpharma/mmrm/blob/c6d2d9c17d23e2fe02268754dbf5fbb22cc6554d/tests/testthat/test-fit.R#L175-L180). The second time does not produce a test failure in the CRAN logs.

**Comment by danielinteractive** [comment]
@dgkf Interesting, thanks for pointing that out. Yeah so as discussed, I am a bit lost with this to be honest. The point is that from the method / optimizer itself it should not be stochastic at all. Like there is no randomness that we expect. It could of course be memory leaks on that specific clang and Linux combination (since Debian also has this). But this goes way beyond our capabilities to detect or fix I think.

**Comment by gowerc** [comment]
Just to say I spent another 2+ hours on this today and still could not replicate the bug :( I may have made a mistake on my setup but I tried to write out my full approach here:
https://gist.github.com/gowerc/8a5a001a31b8496e9233056c53a9acbc

This was run on my personal laptop which is Fedora 37 (not 36 which is what CRAN runs) + clang 15. 

Only other thing to do (besides checking my setup is accurate) is to get a docker image for fedora 36 and manually compile clang. Unfortunately that's a little bit outside of my skillset at the moment :cry:  (at least I wouldn't even know where to begin)

**Comment by danielinteractive** [comment]
Thanks @gowerc for investing the time!
So all in all, I don't think we can do more here. Suggest to close this. If we get new ideas we can reopen again

**Comment by dgkf** [comment]
Yeah, I tried forking the rhub builders and wasn't able to get `clang` working without upgrading a ton of packages (effectively upgrading to Fedora 38 Rawhide). At that point, I'm not sure how effectively I'm reproducing the build machine anyways.

**Comment by gowerc** [comment]
Unless CRAN provide a build script to replicate their environment I just don't see this as feasible. Especially when they have notes like this:


>Some external C++ libraries compiled with clang/libc++ are installed under
/usr/local/clang.  Currently
    JAGS ImageMagick boost_program_options gdal poppler protobuf
but subject to change.  Other C++ libraries, e.g. 
GEOS PROJ SYMPHONY zeromq
can use the system builds.
(Boost was built with clang 14 as it fails to compile with 15.)

i.e. they even use different compiler versions for building different libraries without specifying exactly which version or the build commands + flags.

**Comment by danielinteractive** [comment]
ok closing for now - another reason to push the https://r-hub.io/ project I guess

**Comment by danielinteractive** [comment]
Thanks @gowerc for the info! 
Yeah we can recheck it then.
