### ISSUE TITLE
between-within degree of freedom

### ISSUE THREAD

**Issue by clarkliming** [openpharma/mmrm#224]
To do:

- [ ] basic textbook methods:
    - [ ] between: n_subjects - n_parameters
    - [ ] within: n_observations - n_subjects - n_parameters 
- [ ] modified implementations in SAS: algorithm unknown, [user guide](https://documentation.sas.com/doc/en/statug/15.1/statug_mixed_syntax01.htm)
    - [ ] "between-modified" or similar name: n_subjects - n_parameters(of variables that does not change in each subject)
    - [ ] "within-modified" or similar: n_observations - n_subjects - n_parameters (also affected by the number of subjects that has different value)
- [ ] implementations in [parameters](https://github.com/easystats/parameters/blob/main/R/dof_betwithin.R)
    - [ ] seems to follow exactly with the description
- [ ] reference: Schluchter, Mark D., and Janet T. Elashoff. "Small-sample adjustments to tests with unbalanced repeated measures assuming several covariance structures." Journal of Statistical Computation and Simulation 37.1-2 (1990): 69-87.

**Comment by danielinteractive** [comment]
@chstock any opinion from methods perspective on importance of these simple d.f. ?

**Comment by chstock** [comment]
From my point of view, it would indeed be nice to have the between-within in the package. It seems to have relevance, as it is still considered as a comparator in (recent) simulation studies on different types of mixed models and it does not turn out to be generally inferior. It is also the SAS default in PROC MIXED apparently. I would expect it still behaves reasonably well. I am not aware that there are scenarios where the between-within method is clearly preferred, or where it might be useful as a fallback option. There might be cases where someone wants to be consistent with other work where this method has been applied. It would be used rather infrequently, I guess, at least in the pharma space. We do not use it in our routine. Outside of pharma it might be different. There may be less concern and guidance about d.f. methods and greater use of the between-method, since people just sticked to the SAS defaults when fitting mixed models. Overall, I would be in favor of having it as an option. Hope this helps.

**Comment by clarkliming** [comment]
> Right now we have only Residual that works with robust sandwich estimators, maybe we could add this too as options?

or maybe the Satterthwaite d.f.? probably the Satterthwaite is a better choice than between-within

**Comment by danielinteractive** [comment]
I think we should have both

**Comment by clarkliming** [comment]
I will start with Satterthwaite (as `clubSandwich` already has a implementation for that)

**Comment by danjamstat** [comment]
I'm happy to start looking into this.

**Comment by danielinteractive** [comment]
@clarkliming @chstock just discussing with @danjamstat on how this d.f. method is actually defined precisely for the 1- and multi-dimensional contrasts - do you have a definition for that? Unfortunately it seems not obvious neither from the cited paper nor from the SAS manual. Thanks in advance for any pointer :-)

**Comment by clarkliming** [comment]
yes we can implement the "text book" version, and that will be the same as what is implemented in `paramters`. Also need to add details to inform the users that the SAS implementations are quite different from our version.

**Comment by chstock** [comment]
The paper by Schluchter and Elashoff (1990) differentiates by the dfs/test statistics by covariance structure (model type), complete/ incomplete data and estimation method. I think it could also an option to stick to the original paper as far as things are clear, i.e. to provide the between-within method only for a limited set of constellations. This would comprise compound symmetry and 1st order autoregressive (Table 2) and unstructured covariance structure (Table 5), with modification for ML and REML respectively. From a first glance, the `parameters` implementation reminds more of a RI&S model, perhaps what is called a growth curve model in Schluchter and Elashoff (1990). If this it true the code may nevertheless be adapted.

**Comment by danielinteractive** [comment]
OK thanks both - then I would propose to adapt the `parameters` implementation for our package, and see what we get. Then we will also have the "modified" versions which we want to match with SAS results.
I think it would be tricky / clunky to restrict the method to certain covariance structures, so I would hope this will work reasonably across covariance structures.

**Comment by chstock** [comment]
Related but more as an aside here: Yesterday, I discovered an interesting paper by Gosho et al. ([International Statistical Review, 2021](https://onlinelibrary.wiley.com/doi/full/10.1111/insr.12447)) that reviews and compares eight modified covariance estimators to adjust for small-sample bias in MMRMs with missing data. The between-within method is used in the simulations.

**Comment by chstock** [comment]
Another remark on denominator degrees of freedom (potential topic for vignettes rather than programming): I was wondering about what the actual evidence base is for the generally agreed-upon recommendations favoring Kenward-Roger (KR) and Sattherthwaite over alternatives. Also, what may (approximately) constitute a small sample that makes them particularly recommendable? Interstingly, in the well-known textbook by [Fitzmaurice, Laird and Ware (2011)](https://onlinelibrary.wiley.com/doi/book/10.1002/9781119513469), the authors recommend KR and Sattherthwaite for "_small sample sizes_", but also state that "_it must be emphasized that the small sample properties of these approximations have not been extensively studied_" (p. 101). This might not have changed substantially in the past 10 years. At least I am not aware of Would maybe be nice to provide some citable references for recommendations and simulation studies in the vignettes [I will keep in in mind].

**Comment by danjamstat** [comment]
Thanks for the comments, all. I've had the chance to have a better read of the Schluchter and Elashoff paper, and I've looked at Gałecki + Burzykowski (2013) and Pinheiro + Bates (2000), which also cover the method.

I think the `parameters` method is incorrect, if only because they have defined "between" and "within" the wrong way round. Although I don't think they have counted the parameters in the right way either.

My interpretation of the references above is that the method should work as follows:
* A 'within' parameter = a parameter with a value that changes within subjects
* A 'between' parameter = a parameter with a value that changes across subjects, but not within
* Within DoF = n_obs - n_subjects - n_within_parameters
* Between DoF = n_subjects - n_between_parameters (-1 if there is an intercept)
* Assign 'within' DoFs to 'within' parameters and intercept
* Assign 'between' DoFs to 'between' terms

SAS seems to do something a bit different: for 'within' effects it takes into account how many subjects the effect changes within. This probably makes sense, but I'm not yet sure how this is implemented. A couple of other SAS quirks:
* If an unstructured correlation structure is used, then all parameters automatically get assigned the 'between' DoF
* When using a `contrast` statement, the DoF of the contrast is based on whichever term is mentioned last in the statement. So you can reorganise your statement and a different DoF could be used. I don't follow the logic of this, and wonder if using the minimum DoF for whichever parameters are associated with the contrast would make more sense.

**Comment by danielinteractive** [comment]
OK thanks a lot @danjamstat for digging into this! Much appreciated. I would recommend to first write the corresponding section in a new vignette as part of this issue, so that we can align on the methodology (including formulas, explanation, references, etc.). Then in a second step can add the implementation to the same branch. What do you think?

**Comment by chstock** [comment]
@danjamstat, happy to help here if you require.

**Comment by danjamstat** [comment]
Thanks @danielinteractive that sounds good to me. I'll make a start on this - @chstock it would be great if you could help with review?

**Comment by danielinteractive** [comment]
Hi @danjamstat, what is your status on this, any help needed for the vignette? Thanks :-)

**Comment by danjamstat** [comment]
Hi @danielinteractive, I've made a start, and am aiming to have a draft done by the end of this week.

**Comment by danjamstat** [comment]
@chstock @danielinteractive I've added a draft PR with my initial vignette text - feel free to review
