### ISSUE TITLE
Allow dropping response variable in `model.frame()`

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#262]

**Comment by clarkliming** [comment]
potential issue related to na.action. By default we are using `na.omit` in all steps, and, if there are na values, the rows will be removed during model fitting, however the data itself is complete. If we remove some of the variables (I will say, removing "subject var", "visit_var" and "group_var" could lead to issues, adding more rows to it).

I just realize this, during implementation of deleting the response. We will have different rows when we call "model.frame" here. For now we did not run into issue because we just don't have NA values in covariates/visits/subject vars. But better to get the whole 
 dataset with model.frame, and then subset the rows/columns here.

**Comment by danielinteractive** [comment]
Hm just revisiting this task, I cannot find the precedent in the standard R packages that would have this, e.g. https://stat.ethz.ch/R-manual/R-devel/library/stats/html/model.frame.html does not mention this at all. 

@kkmann what was the thing you missed exactly and where did you see that before? We now use https://stat.ethz.ch/R-manual/R-patched/library/stats/html/delete.response.html and maybe we can just keep using that and don't worry about `model.frame()`?

**Comment by danielinteractive** [comment]
I think we can close this, unless somebody feels strongly about it.
