### ISSUE TITLE
Question on covariance estimation with non-overlapping longitudinal data

### ISSUE THREAD

**Issue by cgsimmons822** [openpharma/mmrm#278]
# Summary 
Hello! Thank you for your work on this great package. 

My colleague @bcjaeger and I are analyzing longitudinal data where the study was designed such that there are time points where no IDs have observations at both time points. However, we noticed that mmrm is able to estimate a covariance between these visits. Other R packages such as nlme do not seem to be able to do this. We'd really appreciate if you could explain how you were able to estimate this covariance and how these values should be interpreted. 

``` r
library(mmrm)
library(tidyverse)
library(nlme)

# setup a simulated dataset that matches our study design:

# 4 times total: 1-4
# 2 groups: PBO and TRT
# group TRT has data at times 1, 2, and 4
# group PBO has data at times 1, 2, and 3

dat <- fev_data %>%
  select(FEV1, ARMCD, AVISIT, USUBJID) %>%
  mutate(FEV1 = case_when(ARMCD == "TRT" & AVISIT == "VIS3" ~ NA_real_,
                          ARMCD == "PBO" & AVISIT == "VIS4" ~ NA_real_,
                          TRUE ~ FEV1),
         USUBJID = factor(USUBJID),
         ARMCD = factor(ARMCD),
         AVISIT = factor(AVISIT)) %>%
  drop_na(FEV1)

# structure of our observations
dat %>% 
  count(ARMCD, AVISIT) %>% 
  pivot_wider(names_from = ARMCD, values_from = n)
#> # A tibble: 4 × 3
#>   AVISIT   PBO   TRT
#>   <fct>  <int> <int>
#> 1 VIS1      68    66
#> 2 VIS2      69    71
#> 3 VIS3      71    NA
#> 4 VIS4      NA    67

# Here is our question: how does mmrm obtain covariance estimates
# between times where no ids overlap? For example, there are no 
# people in our data who completed visit 3 and visit 4, but our model
# is able to estimate a covariance between these visits.
mmrm(FEV1 ~ AVISIT + us(AVISIT|USUBJID), 
     data = dat) %>% 
  VarCorr()
#>          VIS1      VIS2      VIS3       VIS4
#> VIS1 49.58699 22.949710 10.050052  25.187032
#> VIS2 22.94971 34.150913  6.307623  22.868341
#> VIS3 10.05005  6.307623 20.043728   5.893978
#> VIS4 25.18703 22.868341  5.893978 116.566182

# it does not seem that nlme can get an estimate for the times with 
# no overlapping people, which is why I wonder how mmrm does it.

lme(FEV1 ~ AVISIT, 
    data = dat,
    random = ~ 1 | USUBJID,
    correlation = corSymm()) %>% 
  getVarCov(type = 'marginal', individuals = c(1:4))
#> USUBJID PT1 
#> Marginal variance covariance matrix
#>        1      2
#> 1 50.282 22.910
#> 2 22.910 50.282
#>   Standard Deviations: 7.091 7.091 
#> USUBJID PT2 
#> Marginal variance covariance matrix
#>        1      2
#> 1 50.282 22.910
#> 2 22.910 50.282
#>   Standard Deviations: 7.091 7.091 
#> USUBJID PT3 
#> Marginal variance covariance matrix
#>        1
#> 1 50.282
#>   Standard Deviations: 7.091 
#> USUBJID PT4 
#> Marginal variance covariance matrix
#>        1      2      3
#> 1 50.282 22.910 13.265
#> 2 22.910 50.282 14.560
#> 3 13.265 14.560 50.282
#>   Standard Deviations: 7.091 7.091 7.091
```
<sup>Created on 2023-05-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

# R session info

``` r 
R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] reprex_2.0.2    nlme_3.1-162    lubridate_1.9.2 forcats_1.0.0   stringr_1.5.0  
 [6] dplyr_1.1.2     purrr_1.0.1     readr_2.1.4     tidyr_1.3.0     tibble_3.2.1   
[11] ggplot2_3.4.2   tidyverse_2.0.0 mmrm_0.2.2     

loaded via a namespace (and not attached):
 [1] gtable_0.3.3        TMB_1.9.4           xfun_0.39           processx_3.8.1     
 [5] lattice_0.21-8      callr_3.7.3         tzdb_0.3.0          numDeriv_2016.8-1.1
 [9] ps_1.7.5            vctrs_0.6.2         tools_4.3.0         Rdpack_2.4         
[13] generics_0.1.3      parallel_4.3.0      sandwich_3.0-2      fansi_1.0.4        
[17] highr_0.10          pkgconfig_2.0.3     Matrix_1.5-4        checkmate_2.2.0    
[21] lifecycle_1.0.3     compiler_4.3.0      munsell_0.5.0       codetools_0.2-19   
[25] htmltools_0.5.5     yaml_2.3.7          pillar_1.9.0        crayon_1.5.2       
[29] MASS_7.3-58.4       multcomp_1.4-23     digest_0.6.31       tidyselect_1.2.0   
[33] mvtnorm_1.1-3       stringi_1.7.12      splines_4.3.0       fastmap_1.1.1      
[37] grid_4.3.0          colorspace_2.1-0    cli_3.6.1           magrittr_2.0.3     
[41] survival_3.5-5      utf8_1.2.3          TH.data_1.1-2       clipr_0.8.0        
[45] withr_2.5.0         scales_1.2.1        backports_1.4.1     estimability_1.4.1 
[49] timechange_0.2.0    rmarkdown_2.21      emmeans_1.8.6       zoo_1.8-12         
[53] hms_1.1.3           evaluate_0.21       knitr_1.42          rbibutils_2.2.13   
[57] rlang_1.1.1         Rcpp_1.0.10         xtable_1.8-4        glue_1.6.2         
[61] rstudioapi_0.14     R6_2.5.1            fs_1.6.2       
```

**Comment by danielinteractive** [comment]
Hi @cgsimmons822 and @bcjaeger, thanks for using `mmrm` and thanks for the question!
It is not a trivial question I think :-) So to be honest I don't have a super good answer to this. 

If we look at our model fitting algorithm described in detail in https://openpharma.github.io/mmrm/latest-tag/articles/algorithm.html, we can see that we use the Cholesky factorization of the unstructured covariance matrix for defining the parameters we use in the optimization of the restricted ML objective function. That is one part of the story I guess, because the Cholesky matrix parameters are overlapping between the different covariance matrix entries. Another thing to be aware of is that we always use the full covariance matrix and then subset the part we actually observe for a subject. 

I guess in order to be sure whether you could trust the estimated covariance between visits 3 and 4, running a small simulation study could be helpful - e.g. assume a true value for the covariance, and see if among 100 simulated data sets it can reliably be estimated. We have done simulation studies before, see the folder https://github.com/openpharma/mmrm/tree/main/simulations for some examples that could be helpful.

**Comment by bcjaeger** [comment]
Hello @danielinteractive, and thanks for the helpful thoughts and suggestion! @cgsimmons822 and I have prepared a small simulation study looking at the estimation of correlation between visits without overlapping people (reprex below). The approach we take with this study is to generate longitudinal data with an unstructured correlation that matches our study design:

- 3 randomized groups
- 4 total time points, 
- each group has a baseline observation (i.e., pre_ex)
- group a has an additional observation at visit 1 (i.e., post_ex_1)
- group b has an additional observation at visit 2 (i.e., post_ex_2)
- group c has an additional observation at visit 3 (i.e., post_ex_3)

So each person has 2 observations and there are a total of 4 time points. There are no persons with data at visits 2 & 3, visits 2 & 4, or visits 3 & 4, so we call these 'visit pairs without overlapping people'

``` r
suppressPackageStartupMessages({
  library(tidyverse)
  library(magrittr)
  library(mvtnorm)
  library(mmrm) 
})

# time values for longitudinal study design
timepoints <- c("pre_ex", "post_ex_1","post_ex_2","post_ex_3")
n_runs <- 100       # number of sim runs
n_grp <- 3          # number of randomized groups
ids_per_grp <- 250  # number of people per group
obs_per_id <- 4     # number of observations per person

# the true correlation matrix among outcome values over time
# off-diag values are arbitrary, but matrix needs to be +semi-def
cor_mat <- matrix(
  data = c( 1.0, -0.2,  0.3, 0.4,
            -0.2,  1.0, -0.2, 0.2,
            0.3, -0.2,  1.0, 0.3,
            0.4,  0.2,  0.3, 1.0),
  nrow = obs_per_id,
  byrow = TRUE
)

# mean values over time
mu_vec <- c(1, 2, 3, 4)

# store bias from each run here
bias <- list()

# reproduce
set.seed(329)

for(i in seq(n_runs)){
  
  # data generating process:
  # 1. simulate multivariate normal data using our specified correlation
  # 2. randomize to groups a, b, or c
  # 3. make group a have observations at pre_ex and post_ex_1
  # 4. make group b have observations at pre_ex and post_ex_2
  # 5. make group c have observations at pre_ex and post_ex_3
  # 6. make time a factor and align its levels with timepoints above
  data_sim <- rmvnorm(n = n_grp * ids_per_grp, 
                      mean = mu_vec, 
                      sigma = cor_mat) %>% 
    set_colnames(timepoints) %>% 
    as_tibble() %>%
    mutate(grp = sample(letters[1:3], size = n(), replace = TRUE)) %>% 
    pivot_longer(-grp, names_to = 'time', values_to = 'y') %>% 
    mutate(
      pid = rep(seq(ids_per_grp * n_grp), each = obs_per_id),
      y = case_when(
        grp == 'a' & !(time %in% c('pre_ex', 'post_ex_1')) ~ NA_real_,
        grp == 'b' & !(time %in% c('pre_ex', 'post_ex_2')) ~ NA_real_,
        grp == 'c' & !(time %in% c('pre_ex', 'post_ex_3')) ~ NA_real_,
        TRUE ~ y
      ),
      .before = grp
    ) %>% 
    mutate(across(-y, factor)) %>% 
    mutate(time = relevel(time, ref = 'pre_ex')) %>% 
    drop_na()
  
  # fit mmrm using a model specification matching data generating process
  fit <- mmrm(formula = y ~ time + us(time | pid), data = data_sim)
  
  bias[[i]] <- VarCorr(fit) %>% 
    cov2cor() %>% 
    subtract(cor_mat)
  
}

# add each bias matrix together, then divide the sum by n_runs
reduce(bias, .f = `+`) / n_runs
#>                 pre_ex    post_ex_1    post_ex_2    post_ex_3
#> pre_ex     0.000000000 -0.008034122  0.009578947  0.008468231
#> post_ex_1 -0.008034122  0.000000000  0.135269702 -0.284920454
#> post_ex_2  0.009578947  0.135269702  0.000000000 -0.173621859
#> post_ex_3  0.008468231 -0.284920454 -0.173621859  0.000000000
```

<sup>Created on 2023-06-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Here are some thoughts we have:

1. the estimation of correlation between visit pairs with overlapping people (i.e., between visit 1 & 2, visit 1 & 3, and visit 1 & 4) is unbiased (i..e, the bias approaches 0).
2. the estimation of correlation between visit pairs without overlapping people (i.e., between visit 2 & 3, visit 2 & 4, and visit 3 & 4) does not seem to be unbiased. 

Following up on a thought you shared above: 

> Another thing to be aware of is that we always use the full covariance matrix and then subset the part we actually observe for a subject.

I wonder if we should apply this idea when we present the estimation of a correlation matrix in our study? In other words, only show the covariance estimates for things we actually observe among our study participants. To clarify what I'm thinking, instead of presenting 

```r
              pre_ex   post_ex_1   post_ex_2   post_ex_3
pre_ex     1.0000000 -0.10449810  0.18552575  0.37521230
post_ex_1 -0.1044981  1.00000000 -0.01938709 -0.03920897
post_ex_2  0.1855258 -0.01938709  1.00000000  0.06961155
post_ex_3  0.3752123 -0.03920897  0.06961155  1.00000000
```

maybe we should present this matrix with visit pairs without overlapping people redacted? i.e., like this:

```r
              pre_ex   post_ex_1   post_ex_2   post_ex_3
pre_ex     1.0000000 -0.10449810  0.18552575  0.37521230
post_ex_1 -0.1044981  1.00000000 ----------  -----------
post_ex_2  0.1855258 ----------- 1.00000000  -----------
post_ex_3  0.3752123 ----------- ---------- 1.00000000
```

To be totally clear, this is not an `mmrm` issue - it is a study design issue. @cgsimmons822 and I are very happy that `mmrm` works with these data and we are looking for expert advice on how to present the results.

**Comment by danielinteractive** [comment]
Hi @bcjaeger , cool! Thanks for looking into this with the simulation study. I guess it is not surprising that the covariance estimates for non-observed pairs don't seem to behave well. So yeah, I think it would make sense to "subset" the covariance matrix afterwards. (I think we could also consider making this a feature in `mmrm` itself...)

**Comment by bcjaeger** [comment]
Awesome - thank you for reviewing! I think that feature would be really nice.

**Comment by cgsimmons822** [comment]
Thank you for the suggestions and helping us think this through!
