### ISSUE TITLE
Explore whether we could add integration tests for `predict` by comparing with SAS `outp/outpm` options

### ISSUE THREAD

**Issue by henrikibster** [openpharma/mmrm#283]
To do:

- [x] Try out below SAS code
- [x] Try to use the `outp` or `outm` options to match `predict` results
- [x] If it works, add a few integration tests

Original issue:
**Summary**

As a statistician/programmer, I want to be able to make predictions from a fitted model using similar syntax to the outp/outpm syntax in SAS.

**Additional Information**

**Comment by danielinteractive** [comment]
Thanks for asking @henrikibster , 

unfortunately I am not very familiar with SAS, and don't know about the `outp/outpm` syntax. Can you please have a look at `?predict` in the latest (basically from today) GitHub version of `mmrm` (check out https://github.com/openpharma/mmrm/blob/main/R/tmb-methods.R#L56) and see if that gives you the predictions you need?
If not can you please specify what is missing? (best in terms of statistics, instead of SAS routines, since I am not familiar with those)

Thanks!

**Comment by henrikibster** [comment]
> Thanks for asking @henrikibster ,
> 
> unfortunately I am not very familiar with SAS, and don't know about the `outp/outpm` syntax. Can you please have a look at `?predict` in the latest (basically from today) GitHub version of `mmrm` (check out https://github.com/openpharma/mmrm/blob/main/R/tmb-methods.R#L56) and see if that gives you the predictions you need? If not can you please specify what is missing? (best in terms of statistics, instead of SAS routines, since I am not familiar with those)
> 
> Thanks!

Thank you very much for the speedy reply!. 
I will have a look at predict from the new release to see if that will fit the purpose. 
I will return if I have any further requests.

**Comment by henrikibster** [comment]
> Thanks @henrikibster , do you maybe have an example SAS code chunk using `outp/outpm`? It could be interesting for us, e.g. to create another integration test vs. SAS results.

Sure. 
Here is some SAS code generating a small example, highligthing the differences between outp and outpm, and specifically that they depend on how you specifiy your random effects - either using the random or the repeated statements. I personally do not like this 'feature' where the output depends on how you specifiy the random effect in SAS. 

* Simulate data - 3 subjects, 2 visits;
data sim;
   call streaminit(1234);
   do subject=1 to 3;
      do visit=1,2;
         y = subject + rand('normal');
         if subject=3 and visit=2 then y = .; /* set one value as missing */
         output;
      end;
   end;
run;

* Run analysis model with subject as a random effect;
proc mixed data=sim;
   class subject visit;
   model y = / outpm=predm1 outp=pred1;
   random subject;
run;

* Run same analysis model parameterised using a repeated statement;
proc mixed data=sim;
   class subject visit;
   model y = / outpm=predm2 outp=pred2;
   repeated visit / subject=subject type=cs;
run;

* Print all predicted values;
proc sql;
   select a.subject
         ,a.visit
         ,a.y
         ,a.pred 'Pred with RANDOM & OUTPM'
         ,b.pred 'Pred with RANDOM & OUTP'
         ,c.pred 'Pred with REPEATED & OUTPM'
         ,d.pred 'Pred with REPEATED & OUTP'
   from predm1 a
   join pred1 b
      on a.subject=b.subject and a.visit=b.visit
   join predm2 c
      on a.subject=c.subject and a.visit=c.visit
   join pred2 d
      on a.subject=d.subject and a.visit=d.visit
   ;
quit;

**Comment by clarkliming** [comment]
after looking at https://support.sas.com/documentation/onlinedoc/stat/131/mixed.pdf, we can, confidently use the sandwich method, instead of using bootstrapping to calculate the variance here https://github.com/openpharma/mmrm/blob/c936694e8a2d417ebd4ab955bcac393b08924b92/R/tmb-methods.R#L100


We adopt the bootstrapping because, we thought it might be true that the non-linear relation of $\theta$ and $\Sigma$ will stop us from using this; but since there is a paper and our gold standard also use this approach we can safely adopt this approach.

Henderson, C. R. (1984), Applications of Linear Models in Animal Breeding, Guelph, ON: University of
Guelph.

Harville, D. A. (1990), “BLUP (Best Linear Unbiased Prediction), and Beyond,” in D. Gianola and K. Hammond, eds., Advances in Statistical Methods for Genetic Improvement of Livestock, volume 18 of Advanced
Series in Agricultural Sciences, 239–276, Berlin: Springer-Verlag

**Comment by danielinteractive** [comment]
Maybe yeah, but for this issue let's focus on the comparisons with SAS. We can always improve things later

**Comment by clarkliming** [comment]
Hi @henrikibster thank you for the nice example. While comparing the results with SAS & R, I am confused that in the SAS proc mixed guide, it says 
![image](https://github.com/openpharma/mmrm/assets/36079400/cddcac93-d1f0-40c1-83c4-9d0109ff0d92)

seems like it is a prediction conditional on existing observations. However, in the example provided,

![image](https://github.com/openpharma/mmrm/assets/36079400/81202157-7c88-4ac9-ba78-90887fc854c0)

I could not get the conditional prediction. Do you know how to enable that? Thank you in advance.

**Comment by henrikibster** [comment]
> Hi @henrikibster thank you for the nice example. While comparing the results with SAS & R, I am confused that in the SAS proc mixed guide, it says ![image](https://user-images.githubusercontent.com/36079400/252659301-cddcac93-d1f0-40c1-83c4-9d0109ff0d92.png)
> 
> seems like it is a prediction conditional on existing observations. However, in the example provided,
> 
> ![image](https://user-images.githubusercontent.com/36079400/252659465-81202157-7c88-4ac9-ba78-90887fc854c0.png)
> 
> I could not get the conditional prediction. Do you know how to enable that? Thank you in advance.

Do you mean the part in the dataset with missing y-value? 
If so I do get that in the output just running the code from above: 
![image](https://github.com/openpharma/mmrm/assets/127318425/db61113a-1074-437c-b809-da72a0d330d1)
