### ISSUE TITLE
formula not parsing data object when formula is y~.

### ISSUE THREAD

**Issue by yonicd** [openpharma/mmrm#293]
when using recipes the formula that is passed into mmrm is of the form `y~.` which is a valid r formula, but it needs to see the data object to work.

the way mmrm is set up now that information doesnt get passed into the underlying function that parses the formula [here](https://github.com/openpharma/mmrm/blob/main/R/utils-formula.R#L12) and then [here](https://github.com/openpharma/mmrm/blob/main/R/utils-nse.R#L92)

```r
debug at C:/projects/mmrm/R/utils-formula.R#12: terms <- stats::terms(formula_rhs(f), specials = specials)
print(f)
..y ~ .
<environment: 0x000001dbf9005928>
Browse[2]> f[-2]
~.
<environment: 0x000001dbf9005928>
```

``` r
library(mmrm, quietly = TRUE)
library(tidymodels, quietly = TRUE)
#> Warning: package 'tidymodels' was built under R version 4.2.3
#> 
#> Warning: package 'broom' was built under R version 4.2.3
#> Warning: package 'dials' was built under R version 4.2.3
#> Warning: package 'scales' was built under R version 4.2.2
#> Warning: package 'dplyr' was built under R version 4.2.3
#> Warning: package 'ggplot2' was built under R version 4.2.3
#> Warning: package 'infer' was built under R version 4.2.3
#> Warning: package 'modeldata' was built under R version 4.2.3
#> Warning: package 'parsnip' was built under R version 4.2.3
#> Warning: package 'purrr' was built under R version 4.2.2
#> Warning: package 'recipes' was built under R version 4.2.3
#> Warning: package 'rsample' was built under R version 4.2.3
#> Warning: package 'tibble' was built under R version 4.2.3
#> Warning: package 'tidyr' was built under R version 4.2.2
#> Warning: package 'tune' was built under R version 4.2.3
#> Warning: package 'workflows' was built under R version 4.2.3
#> Warning: package 'workflowsets' was built under R version 4.2.3
#> Warning: package 'yardstick' was built under R version 4.2.3
mmrm_recipe <- recipe(FEV1 ~ RACE + ARMCD + AVISIT, data = fev_data) |>
  step_dummy(ARMCD) |>
  step_interact(terms = ~starts_with('ARMCD'):AVISIT)

mmrm_spec_with_cov <- linear_reg() |>
  set_engine("mmrm", 
             method = 'Satterthwaite', 
             covariance = as.cov_struct(~us(AVISIT | USUBJID)))

(mmrm_wflow_nocov <- workflow() |>
    add_model(mmrm_spec_with_cov) |>
    add_recipe(mmrm_recipe))
#> ══ Workflow ════════════════════════════════════════════════════════════════════
#> Preprocessor: Recipe
#> Model: linear_reg()
#> 
#> ── Preprocessor ────────────────────────────────────────────────────────────────
#> 2 Recipe Steps
#> 
#> • step_dummy()
#> • step_interact()
#> 
#> ── Model ───────────────────────────────────────────────────────────────────────
#> Linear Regression Model Specification (regression)
#> 
#> Engine-Specific Arguments:
#>   method = Satterthwaite
#>   covariance = as.cov_struct(~us(AVISIT | USUBJID))
#> 
#> Computational engine: mmrm

fit(mmrm_wflow_nocov, data = fev_data)
#> Error in terms.formula(formula_rhs(f), specials = specials): '.' in formula and no 'data' argument
details::details(sessioninfo::session_info(), summary = 'si')
```

<details closed>
<summary>
<span title="Click to Expand"> si </span>
</summary>

``` r

─ Session info ───────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.1 (2022-06-23 ucrt)
 os       Windows 10 x64 (build 19044)
 system   x86_64, mingw32
 ui       RTerm
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       America/New_York
 date     2023-06-14
 pandoc   3.1.1 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)

─ Packages ───────────────────────────────────────────────────────────────────
 package      * version    date (UTC) lib source
 backports      1.4.1      2021-12-13 [1] CRAN (R 4.2.0)
 broom        * 1.0.4      2023-03-11 [1] CRAN (R 4.2.3)
 checkmate      2.2.0      2023-04-27 [1] CRAN (R 4.2.3)
 class          7.3-20     2022-01-16 [3] CRAN (R 4.2.1)
 cli            3.6.1      2023-03-23 [1] CRAN (R 4.2.3)
 clipr          0.8.0      2022-02-22 [1] CRAN (R 4.2.1)
 codetools      0.2-18     2020-11-04 [3] CRAN (R 4.2.1)
 colorspace     2.1-0      2023-01-23 [1] CRAN (R 4.2.2)
 data.table     1.14.2     2021-09-27 [1] CRAN (R 4.2.1)
 desc           1.4.2      2022-09-08 [1] CRAN (R 4.2.1)
 details        0.3.0      2022-03-27 [1] CRAN (R 4.2.2)
 dials        * 1.2.0      2023-04-03 [1] CRAN (R 4.2.3)
 DiceDesign     1.9        2021-02-13 [1] CRAN (R 4.2.3)
 digest         0.6.31     2022-12-11 [1] CRAN (R 4.2.2)
 dplyr        * 1.1.2      2023-04-20 [1] CRAN (R 4.2.3)
 ellipsis       0.3.2      2021-04-29 [1] CRAN (R 4.2.2)
 evaluate       0.21       2023-05-05 [1] CRAN (R 4.2.3)
 fansi          1.0.4      2023-01-22 [1] CRAN (R 4.2.2)
 fastmap        1.1.0      2021-01-25 [1] CRAN (R 4.2.1)
 foreach        1.5.2      2022-02-02 [1] CRAN (R 4.2.3)
 fs             1.6.2      2023-04-25 [1] CRAN (R 4.2.3)
 furrr          0.3.1      2022-08-15 [1] CRAN (R 4.2.3)
 future         1.32.0     2023-03-07 [1] CRAN (R 4.2.3)
 future.apply   1.11.0     2023-05-21 [1] CRAN (R 4.2.3)
 generics       0.1.3      2022-07-05 [1] CRAN (R 4.2.3)
 ggplot2      * 3.4.2      2023-04-03 [1] CRAN (R 4.2.3)
 globals        0.16.2     2022-11-21 [1] CRAN (R 4.2.2)
 glue           1.6.2      2022-02-24 [1] CRAN (R 4.2.2)
 gower          1.0.1      2022-12-22 [1] CRAN (R 4.2.2)
 GPfit          1.0-8      2019-02-08 [1] CRAN (R 4.2.3)
 gtable         0.3.2      2023-03-17 [1] CRAN (R 4.2.1)
 hardhat        1.3.0      2023-03-30 [1] CRAN (R 4.2.3)
 highr          0.9        2021-04-16 [1] CRAN (R 4.2.1)
 htmltools      0.5.4      2022-12-07 [1] CRAN (R 4.2.2)
 httr           1.4.4      2022-08-17 [1] CRAN (R 4.2.1)
 infer        * 1.0.4      2022-12-02 [1] CRAN (R 4.2.3)
 ipred          0.9-14     2023-03-09 [1] CRAN (R 4.2.3)
 iterators      1.0.14     2022-02-05 [1] CRAN (R 4.2.3)
 knitr          1.41       2022-11-18 [1] CRAN (R 4.2.2)
 lattice        0.21-8     2023-04-05 [1] CRAN (R 4.2.3)
 lava           1.7.2.1    2023-02-27 [1] CRAN (R 4.2.3)
 lhs            1.1.6      2022-12-17 [1] CRAN (R 4.2.3)
 lifecycle      1.0.3      2022-10-07 [1] CRAN (R 4.2.2)
 listenv        0.9.0      2022-12-16 [1] CRAN (R 4.2.3)
 lubridate      1.9.2      2023-02-10 [1] CRAN (R 4.2.3)
 magrittr       2.0.3      2022-03-30 [1] CRAN (R 4.2.2)
 MASS           7.3-58.1   2022-08-03 [1] CRAN (R 4.2.2)
 Matrix         1.5-4.1    2023-05-18 [1] CRAN (R 4.2.3)
 mmrm         * 0.2.2.9017 2023-06-01 [1] local
 modeldata    * 1.1.0      2023-01-25 [1] CRAN (R 4.2.3)
 munsell        0.5.0      2018-06-12 [1] CRAN (R 4.2.2)
 nlme           3.1-162    2023-01-31 [1] CRAN (R 4.2.3)
 nnet           7.3-17     2022-01-16 [3] CRAN (R 4.2.1)
 numDeriv       2016.8-1.1 2019-06-06 [1] CRAN (R 4.2.0)
 parallelly     1.35.0     2023-03-23 [1] CRAN (R 4.2.3)
 parsnip      * 1.1.0      2023-04-12 [1] CRAN (R 4.2.3)
 pillar         1.9.0      2023-03-22 [1] CRAN (R 4.2.3)
 pkgconfig      2.0.3      2019-09-22 [1] CRAN (R 4.2.2)
 png            0.1-8      2022-11-29 [1] CRAN (R 4.2.2)
 prodlim        2023.03.31 2023-04-02 [1] CRAN (R 4.2.3)
 purrr        * 1.0.1      2023-01-10 [1] CRAN (R 4.2.2)
 R.cache        0.16.0     2022-07-21 [1] RSPM (R 4.2.0)
 R.methodsS3    1.8.2      2022-06-13 [1] CRAN (R 4.2.0)
 R.oo           1.25.0     2022-06-12 [1] CRAN (R 4.2.0)
 R.utils        2.12.2     2022-11-11 [1] CRAN (R 4.2.3)
 R6             2.5.1      2021-08-19 [1] CRAN (R 4.2.2)
 rbibutils      2.2.13     2023-01-13 [1] CRAN (R 4.2.3)
 Rcpp           1.0.10     2023-01-22 [1] CRAN (R 4.2.2)
 Rdpack         2.4        2022-07-20 [1] CRAN (R 4.2.1)
 recipes      * 1.0.6      2023-04-25 [1] CRAN (R 4.2.3)
 reprex         2.0.2      2022-08-17 [1] CRAN (R 4.2.2)
 rlang          1.1.1      2023-04-28 [1] CRAN (R 4.2.3)
 rmarkdown      2.19       2022-12-15 [1] CRAN (R 4.2.2)
 rpart          4.1.16     2022-01-24 [3] CRAN (R 4.2.1)
 rprojroot      2.0.3      2022-04-02 [1] CRAN (R 4.2.1)
 rsample      * 1.1.1      2022-12-07 [1] CRAN (R 4.2.3)
 rstudioapi     0.14       2022-08-22 [1] CRAN (R 4.2.2)
 scales       * 1.2.1      2022-08-20 [1] CRAN (R 4.2.2)
 sessioninfo    1.2.2      2021-12-06 [1] CRAN (R 4.2.2)
 stringi        1.7.12     2023-01-11 [1] CRAN (R 4.2.2)
 stringr        1.5.0      2022-12-02 [1] CRAN (R 4.2.2)
 styler         1.9.1      2023-03-04 [1] CRAN (R 4.2.3)
 survival       3.3-1      2022-03-03 [3] CRAN (R 4.2.1)
 tibble       * 3.2.1      2023-03-20 [1] CRAN (R 4.2.3)
 tidymodels   * 1.1.0      2023-05-01 [1] CRAN (R 4.2.3)
 tidyr        * 1.3.0      2023-01-24 [1] CRAN (R 4.2.2)
 tidyselect     1.2.0      2022-10-10 [1] CRAN (R 4.2.2)
 timechange     0.2.0      2023-01-11 [1] CRAN (R 4.2.3)
 timeDate       4022.108   2023-01-07 [1] CRAN (R 4.2.3)
 tune         * 1.1.1      2023-04-11 [1] CRAN (R 4.2.3)
 utf8           1.2.3      2023-01-31 [1] CRAN (R 4.2.2)
 vctrs          0.6.2      2023-04-19 [1] CRAN (R 4.2.3)
 withr          2.5.0      2022-03-03 [1] CRAN (R 4.2.2)
 workflows    * 1.1.3      2023-02-22 [1] CRAN (R 4.2.3)
 workflowsets * 1.0.1      2023-04-06 [1] CRAN (R 4.2.3)
 xfun           0.35       2022-11-16 [1] CRAN (R 4.2.2)
 xml2           1.3.3      2021-11-30 [1] CRAN (R 4.2.1)
 yaml           2.3.6      2022-10-18 [1] CRAN (R 4.2.2)
 yardstick    * 1.2.0      2023-04-21 [1] CRAN (R 4.2.3)

 [1] C:/Users/jonathan.sidi/AppData/Local/R/win-library/4.2
 [2] C:/Users/jonathan.sidi/AppData/Local/Programs/R/R-4.2.1/site-library
 [3] C:/Users/jonathan.sidi/AppData/Local/Programs/R/R-4.2.1/library

──────────────────────────────────────────────────────────────────────────────
```

</details>

<br>

<sup>Created on 2023-06-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by danielinteractive** [comment]
Maybe also good for @dgkf to have a look

**Comment by danielinteractive** [comment]
Hm I am not so sure about the `tidymodels` way of usage here, but if we have both the formula `y ~ .` plus the covariance term e.g. `us(visit | id)` then we could make as a default convention that `.` just includes all columns except `y, visit, id`. And if the user does not like that they need to specify the formula explicitly. Wdyt @yonicd ?

**Comment by clarkliming** [comment]
current solution is difficult. in `recipe()` to prepare data, it is not dependent on the model, so the created data contains no "USUBJID" or "AVISIT" (the covariance term is not included).  So in model we should add that "USUBJID" and "AVISIT" in the formula to make the recipe keep the data (otherwise it will be dropped)

That leads to these variables indistinguishable...

**Comment by clarkliming** [comment]
some though: add some `step` to add `id`, `timepoint` and `group` variables (importantly, they should be not of the same name as formula names). These variables will always be removed so that it won't affect the model fitting with `.`. (at this timepoint, the AVISIT and "timepoint" are two different names now)

**Comment by dgkf** [comment]
I think this is two separate issues:

1. Are we missing something in our `tidymodels` integration that results in an interal error when it tries to fit a `y ~ .` model?
1. Can (should?) we handle the `.` syntax in our model formulas?

## On the internal use of `y ~ .`

@yonicd - If I'm understanding your example correctly, you're expecting to a fit a model with (roughly) the formula below:

```
FEV1 ~ RACE + ARMCD + AVISIT + us(AVISIT | USUBJID)
```

In this case, if I'm understanding the example correctly, `y ~ .` is somehow being used within `tidymodels`, and is not the user-provided formula that you want to fit a model on. 

If that's the case, instead of focusing on how `.` should behave, I think we should be focusing on what we're missing in the `tidymodels` interface that is not operating properly on the intended formula. 

I believe that `tidymodels` filters the data that is passed to the model when it preprocesses the data in the recipe steps. This includeds dummy-ing of `ARMCD` into separate, presumably one-hot-encoded variables and creating new variables for all the interaction terms. Then this generalized dataset with each term as a variable is fit with a generic `y ~ .` model under the hood.

In that case, I think we should dissect this tidymodels execution model and make sure that it can be accommodated by the way `mmrm` is expecting its model specifications and data.

## On `.` syntax

To work with tidymodels, I'm under the impression that we want this to work idiomatically - expanding to all non-dependent variables. However, that might be different from what would be the "statistically correct" thing to do outside of tidymodels.

Given the choice between _doing the statistically-correct thing_ with `.` (omitting covariance structure terms), and _doing the R-stats-idiomatic thing_ with `.` (expanding to all non-dependent variables), I almost always lean toward existing idioms. Even if you can shoot yourself in the foot using `.`, it would be even more confusing if it were to work different from any other model formula.

**Comment by yonicd** [comment]
tidymodels passes in the covariates from the derived design matrix created from recipe. it is using `y~.` formula structure, which is supported in lm, glm, lmer,....

this is what recipes creates

```r
mmrm_recipe <- recipe(FEV1 ~ RACE + ARMCD + AVISIT, data = fev_data) |>
  step_dummy(ARMCD) |>
  step_interact(terms = ~ starts_with("ARMCD"):AVISIT)

mmrm_recipe |>
  prep() |>
  juice()
```

```r
# A tibble: 800 × 7
   RACE                AVISIT  FEV1 ARMCD_TRT ARMCD_TRT_x_AVISITVIS2 ARMCD_TRT_x_AVISITVIS3
   <fct>               <fct>  <dbl>     <dbl>                  <dbl>                  <dbl>
 1 Black or African A… VIS1    NA           1                      0                      0
 2 Black or African A… VIS2    40.0         1                      1                      0
 3 Black or African A… VIS3    NA           1                      0                      1
 4 Black or African A… VIS4    20.5         1                      0                      0
 5 Asian               VIS1    NA           0                      0                      0
 6 Asian               VIS2    31.5         0                      0                      0
 7 Asian               VIS3    36.9         0                      0                      0
 8 Asian               VIS4    48.8         0                      0                      0
 9 Black or African A… VIS1    NA           0                      0                      0
10 Black or African A… VIS2    36.0         0                      0                      0
# ℹ 790 more rows
# ℹ 1 more variable: ARMCD_TRT_x_AVISITVIS4 <dbl>
# ℹ Use `print(n = ...)` to see more rows
```

**Comment by yonicd** [comment]
tidymodels doesnt fit anything itself perse. it just passes in data into the mmrm fit function.

**Comment by yonicd** [comment]
we can use in the recipe a step to define roles for variables too if we need to keep that info in the data attributes

**Comment by dgkf** [comment]
Thanks for breaking that down for me. It's been a while since I was using `tidymodels` regularly. 

Then I'm hearing that we have two design considerations to work around:
- When `fit` is called, `USUBJID` won't be available for the covariance structure that you pass in `set_engine`. 
- If it is in the data, we'd need a way to remove it before running the generic model as `y ~ .` model.

I recall using `tidymodels`' [_roles_](https://www.tidymodels.org/start/recipes/index.html#recipe), which might let us use preprocessing steps to simply flag unused, but necessary covariance structure variables (credit to @clarkliming who suggested this above as well). Then we can remove them in our `fit` function. Depending on what facets we have for attaching data to the recipe, we might be able to also bind the covariance structure definition. 

I'm imagining something that looks like:

```r
mmrm_recipe <- recipe(FEV1 ~ RACE + ARMCD + AVISIT, data = fev_data) |>
  step_dummy(ARMCD) |>
  step_interact(terms = ~starts_with('ARMCD'):AVISIT) |>
  # 1. add roles "mmrm_covstruct_{id,group,timepoint}" to respective columns,
  #   ideally binds covstruct object to tibble
  step_mmrm_cov_struct(terms = ~us(AVISIT | USUBJID))  

mmrm_spec_with_cov <- linear_reg() |>
  set_engine("mmrm", method = 'Satterthwaite')

# 2. register tidymodels-specific `fit` function that:
#    - derives formula on subset of data excluding `mmrm_covstruct_*` role variables
#    - extracts covariance structure definition from recipe output
#    - calls mmrm()
mmrm_wflow_nocov <- workflow() |>
  add_model(mmrm_spec_with_cov) |>
  add_recipe(mmrm_recipe)
```

The part I'm least confident in is attaching this covariance structure info to this data. Hopefully there's a built-in way to bind associated data to a recipe, but if not, the paths I see are:
- bind a covariance structure as an attribute of the recipe data. But since each step has free reign to modify it. Even if it works with the off-the-shelf recipes steps, you'd be at the mercy of other package steps to preserve attributes. 
- Introduce a column that is effectively just used to shove the covariance object into the first element, but that has a pretty gnarly code smell to it. 
- Provide the covariance structure to both the recipe and in the model spec... which also has some pretty bad code smell.
- use `broom::augment` to deconstruct a covariance structure object into separate columns. I don't think there's really ever a need to have a different covariance structure definition per observation, so it's effectively just "tidyness for tidyness sake" as a way of achieving the same goal as above.

Reconstructing a formula + covariance structure:
- I think this part is more straightforward. If we have roles for all covariance structure data, then we can reconstruct the appropriate formula and covariance definition in a pre-processing step, and just [register that to `parsnip`](https://github.com/openpharma/mmrm/blob/main/R/interop-parsnip.R#L43) instead of using `mmrm` directly.

**Comment by clarkliming** [comment]
after some explore... I found the following

1. if we still use `linear_reg()` as our starting point, it will be of class `model_spec` and `fit.model_spec` prevent us from constructing the new call
2. using `step_mmrm_cov` is difficut
    1. in recipe, we have to provide all terms to allow it be used in later steps. so we can not use `recipe(FEV1 ~ RACE + ARMCD)` and later add `add_role(USUBJID, "ID")`. this will give error that `USUBJID` does not exist
    2. we have to use `recipe(FEV1 ~ RACE + ARMCD + USUBJID + AVISIT)`
    3. even its role is updated, it wont enter the data after baking ( only predictor and response are kept. but we do need thes variables baked in the resulting data.frame)

it seems that there are a lot of efforts needed to make mmrm compatible with `workflows`

**Comment by danielinteractive** [comment]
Thanks @dgkf and @clarkliming for looking into it!
Vague idea from the sidelines: Is there something we can learn from other package interfaces with tidymodels, e.g. `glmmTMB` or `lme4`? I think they have a similar formula interface compared to us. So I wonder if we can learn something from them.

**Comment by dgkf** [comment]
Thanks for the nudge, @danielinteractive - Looking at the tidymodels interface for `lme`, it looks like the default behavior also [struggles to handling recipes gracefully](https://multilevelmod.tidymodels.org/articles/multilevelmod.html#using-tidymodels-workflows). Instead, it looks like these types of models with some sort of multilevel structure are better suited for being defined in the workflow directly:

```r
lmer_spec <- 
  linear_reg() %>% 
  set_engine("lmer")

lmer_wflow <- 
  workflow() %>% 
  add_variables(outcomes = Reaction, predictors = c(Days, Subject)) %>% 
  add_model(lmer_spec, formula = Reaction ~ Days + (1|Subject))

lmer_wflow %>% fit(data = sleepstudy)
```

Notably:
1. It avoids the use of a recipe, opting instead to use `add_variables` and `add_model` as part of the workflow
2. All necessary variables (including covariance structure terms) would be passed to `add_variables(predictors = )`

The vignette does provide a recipe example further down, but it runs into the same headaches that we're having here - being very mindful of juggling the multilevel terms and making sure not to apply any preprocessing steps to them. If this is the suggested workflow, I'd say we should favor the `add_variables`/`add_model` style and just consider the recipe-style definition a "at your own risk" use case.

That said, I think we might still want to wrap `mmrm()` in a `parsnip`-specific wrapping function that can try to anticipate some common `tidymodels`-specific footguns and provide more specific suggestions in its error messages.

**Comment by yonicd** [comment]
the pr w the vignette for tidymodels has the basic steps that are possible now

**Comment by yonicd** [comment]
sounds good.

**Comment by danielinteractive** [comment]
Just discussed with @yonicd . This is a general question for `mmrm` package that we could make the `.` thing working somehow...
