### ISSUE TITLE
REPEATED and random intercept models are not supported？

### ISSUE THREAD

**Issue by kunghiu** [openpharma/mmrm#389]
Dear all.

As I know, repeated models and random intercept models are also commonly used in trials.

Additionally, covariance structure TYPE=FA0(2) is also needed.

So far, I cannot apply them with mmrm. If these features are already included in mmrm, Please let me know. 

Thank you.

**Comment by danielinteractive** [comment]
Hi @kunghiu ,

thanks for the feedback!

- Regarding random intercept, this is discussed in https://github.com/openpharma/mmrm/issues/300 please feel free to add there further thoughts
- For FA0(2) I understand from https://documentation.sas.com/doc/en/statcdc/14.2/statug/statug_mixed_syntax14.htm#statug.mixed.mixedcovstruct and the corresponding details that this is only useful in combination with random effects, because it is not positive definite when having more than 2 time points. Can you maybe say more here why you need FA0(2), maybe with an example?

**Comment by kunghiu** [comment]
Thank you for your reply, @danielinteractive .

In this FDA guidance, https://www.fda.gov/regulatory-information/search-fda-guidance-documents/statistical-approaches-establishing-bioequivalence-0, and many draft guidances before this one, they all use FA0(2) in proc mixed model. And this has become a standard procedure in the whole ANDA statistics. Softwares like winnonlin, they all mimic SAS and use FA0(2) structure.

However, if mmrm donot solve SAS REPEATED-like clause, only FA0(2) being added is valueless.

**Comment by kunghiu** [comment]
Thank you for your reply, @danielinteractive .

In this FDA guidance, https://www.fda.gov/regulatory-information/search-fda-guidance-documents/statistical-approaches-establishing-bioequivalence-0, and many draft guidances before this one, they all use FA0(2) in proc mixed model. And this has become a standard procedure in the whole ANDA statistics. Softwares like winnonlin, they all mimic SAS and use FA0(2) structure.

However, if mmrm donot solve SAS REPEATED-like clause, only FA0(2) being added is valueless.

**Comment by danielinteractive** [comment]
Thanks @kunghiu , that is helpful - in that case I will close this issue and discussion can be continued in #300 , I will add the FDA's draft guidance snippet there
